// Root layout dell'App Router: avvolge ogni pagina con i Provider globali
// (sessione Auth.js, React Query) e un header comune con navigazione e
// logout, sempre visibile indipendentemente dalla rotta.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { LogoutButton } from "@/components/logout-button";
import { NavLinks } from "@/components/nav-links";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Providers: qui vivono SessionProvider (Auth.js) e QueryClientProvider
            (React Query), condivisi da tutte le pagine client sotto. */}
        <Providers>
          <header className="flex items-center justify-between border-b border-zinc-200 px-4 py-3 dark:border-zinc-800">
            {/* NavLinks mostra/nasconde i link in base a sessione e ruolo
                dell'utente corrente (vedi src/components/nav-links.tsx). */}
            <NavLinks />
            <LogoutButton />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
